package com.freeconductor.ui.cluster

object BrokerPropertyDescriptions {
    private val map = mapOf(
        "advertised.listeners" to "Listeners to publish to ZooKeeper for clients to use, if different from the listeners config property.",
        "auto.create.topics.enable" to "Enable auto creation of a topic on the server.",
        "auto.leader.rebalance.enable" to "Enables automatic leader balancing on the cluster.",
        "background.threads" to "The number of threads to use for various background processing tasks.",
        "broker.id" to "The broker id for this server.",
        "broker.rack" to "Rack of the broker. Used in rack-aware replication assignment for fault tolerance.",
        "compression.type" to "Specify the final compression type for a given topic. Accepts: gzip, snappy, lz4, zstd, uncompressed, producer.",
        "connections.max.idle.ms" to "Idle connections timeout: the server socket processor threads close connections that have been idle for longer than this.",
        "controlled.shutdown.enable" to "Enable controlled shutdown of the server.",
        "controlled.shutdown.max.retries" to "The number of retries for a controlled shutdown.",
        "default.replication.factor" to "The default replication factor for automatically created topics.",
        "delete.topic.enable" to "Enables delete topic. Delete topic through the admin tool will have no effect if this config is turned off.",
        "inter.broker.protocol.version" to "Specify which version of the inter-broker protocol will be used.",
        "leader.imbalance.check.interval.seconds" to "The frequency with which the partition rebalance check is triggered by the controller.",
        "leader.imbalance.per.broker.percentage" to "The ratio of leader imbalance allowed per broker before the controller triggers a leader balance.",
        "log.cleaner.enable" to "Enable the log cleaner process to run on the server.",
        "log.flush.interval.messages" to "The number of messages accumulated on a log partition before messages are flushed to disk.",
        "log.flush.interval.ms" to "The maximum time in ms that a message in any topic is kept in memory before flushed to disk.",
        "log.retention.bytes" to "The maximum size of the log before deleting it. -1 means no limit.",
        "log.retention.hours" to "The number of hours to keep a log file before deleting it.",
        "log.retention.ms" to "The milliseconds to keep a log file before deleting it.",
        "log.roll.ms" to "The maximum time before a new log segment is rolled out (in milliseconds).",
        "log.segment.bytes" to "The maximum size of a single log file.",
        "max.connections" to "The maximum number of connections allowed in the broker at any time.",
        "max.connections.per.ip" to "The maximum number of connections allowed from each IP address.",
        "message.max.bytes" to "The largest record batch size allowed by Kafka (after compression if compression is enabled).",
        "min.insync.replicas" to "When a producer sets acks to 'all', the minimum number of replicas that must acknowledge a write for it to be considered successful.",
        "num.io.threads" to "The number of threads that the server uses for processing requests, which may include disk I/O.",
        "num.network.threads" to "The number of threads the server uses for receiving requests from the network and sending responses.",
        "num.partitions" to "The default number of log partitions per topic.",
        "num.recovery.threads.per.data.dir" to "The number of threads per data directory used for log recovery at startup and flushing at shutdown.",
        "num.replica.fetchers" to "Number of fetcher threads used to replicate records from each source broker.",
        "offsets.retention.minutes" to "After a consumer group loses all its consumers, its offsets will be kept for this retention period before being discarded.",
        "replica.fetch.max.bytes" to "The number of bytes of messages to attempt to fetch for each partition.",
        "replica.lag.time.max.ms" to "If a follower hasn't sent any fetch requests or consumed up to the leader's log end offset for at least this time, the leader will remove the follower from ISR.",
        "request.timeout.ms" to "The maximum amount of time the client will wait for the response of a request.",
        "socket.receive.buffer.bytes" to "The SO_RCVBUF buffer of the socket server sockets. If -1, the OS default will be used.",
        "socket.request.max.bytes" to "The maximum number of bytes in a socket request.",
        "socket.send.buffer.bytes" to "The SO_SNDBUF buffer of the socket server sockets. If -1, the OS default will be used.",
        "transaction.max.timeout.ms" to "The maximum allowed timeout for transactions.",
        "unclean.leader.election.enable" to "Indicates whether to enable replicas not in the ISR set to be elected as leader as a last resort, even though doing so may result in data loss.",
        "zookeeper.connection.timeout.ms" to "The max time that the client waits to establish a connection to ZooKeeper.",
        "zookeeper.session.timeout.ms" to "ZooKeeper session timeout.",
    )

    fun get(name: String): String = map[name] ?: ""
}
